import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  bytesToBase64,
  encodeEmbeddingFile
} from "../src/lib/embeddings";
import { DEFAULT_EMBEDDING_MODEL, EMBEDDING_DIMENSIONS } from "../src/lib/constants";
import { localEmbedding } from "../src/lib/local-embedding";
import type { EmbeddingManifest, Watch } from "../src/types";
import { loadLocalSecrets, secretValue } from "./shared/secrets";

const root = resolve(import.meta.dirname, "..");
const dataDirectory = resolve(root, "src/data");
const catalog = JSON.parse(await readFile(resolve(dataDirectory, "catalog.json"), "utf8")) as Watch[];
const secrets = await loadLocalSecrets(root);
const apiKey = process.env.OPENAI_API_KEY ?? secretValue(secrets.openai?.api_key);
const model = process.env.OPENAI_EMBEDDING_MODEL ?? secretValue(secrets.openai?.embedding_model) ?? DEFAULT_EMBEDDING_MODEL;
const forceLocal = process.argv.includes("--local");
const requireOpenAI = process.argv.includes("--require-openai");

if (requireOpenAI && !apiKey) {
  throw new Error("OPENAI_API_KEY is required. Add it to secrets.yaml or the environment.");
}

async function openAIEmbeddings(input: string[]): Promise<number[][]> {
  if (!apiKey) throw new Error("OPENAI_API_KEY is not configured.");
  const all: number[][] = [];
  for (let start = 0; start < input.length; start += 100) {
    const batch = input.slice(start, start + 100);
    const response = await fetch("https://api.openai.com/v1/embeddings", {
      method: "POST",
      headers: {
        authorization: `Bearer ${apiKey}`,
        "content-type": "application/json"
      },
      body: JSON.stringify({
        model,
        input: batch,
        dimensions: EMBEDDING_DIMENSIONS,
        encoding_format: "float"
      })
    });
    if (!response.ok) throw new Error(`OpenAI embeddings failed (${response.status}): ${await response.text()}`);
    const payload = await response.json() as {
      data: Array<{ index: number; embedding: number[] }>;
    };
    const ordered = payload.data.sort((a, b) => a.index - b.index).map((item) => item.embedding);
    if (ordered.length !== batch.length || ordered.some((vector) => vector.length !== EMBEDDING_DIMENSIONS)) {
      throw new Error("OpenAI returned an unexpected embedding shape.");
    }
    all.push(...ordered);
  }
  return all;
}

const descriptions = catalog.map((watch) => watch.styleDescription);
const useOpenAI = Boolean(apiKey) && !forceLocal;
const vectors = useOpenAI
  ? await openAIEmbeddings(descriptions)
  : descriptions.map((description) => localEmbedding(description, EMBEDDING_DIMENSIONS));
const bytes = encodeEmbeddingFile(vectors);
const contentHash = createHash("sha256")
  .update(JSON.stringify(catalog.map(({ id, styleDescription }) => ({ id, styleDescription }))))
  .update(useOpenAI ? model : "local-hash-v1")
  .digest("hex");
const manifest: EmbeddingManifest = {
  version: 1,
  provider: useOpenAI ? "openai" : "local-hash",
  model: useOpenAI ? model : "local-hash-v1",
  dimensions: EMBEDDING_DIMENSIONS,
  count: catalog.length,
  ids: catalog.map((watch) => watch.id),
  contentHash,
  generatedAt: new Date().toISOString(),
  quantization: "symmetric-int8"
};
const base64 = bytesToBase64(bytes);
const generatedModule = `// Generated by scripts/build-embeddings.ts. Do not edit.\n` +
  `import type { EmbeddingManifest } from "../types";\n\n` +
  `export const EMBEDDINGS_BASE64 = ${JSON.stringify(base64)};\n` +
  `export const EMBEDDINGS_MANIFEST: EmbeddingManifest = ${JSON.stringify(manifest, null, 2)};\n`;

await mkdir(dataDirectory, { recursive: true });
await Promise.all([
  writeFile(resolve(dataDirectory, "embeddings.bin"), bytes),
  writeFile(resolve(dataDirectory, "embeddings.manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`),
  writeFile(resolve(dataDirectory, "embeddings.generated.ts"), generatedModule)
]);
console.log(`Built ${catalog.length} × ${EMBEDDING_DIMENSIONS} ${manifest.provider} embeddings (${Math.round(bytes.byteLength / 1024)}KB int8).`);
if (!useOpenAI) console.warn("Local-hash fallback built. Re-run with OPENAI_API_KEY for production semantic search.");
